// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTlI_cmmqjf5FPHHUcMUHq56pwifwq_FE',
    appId: '1:1015423722551:web:50fb2e3b39d7c06279cbb2',
    messagingSenderId: '1015423722551',
    projectId: 'gobuddy-at1435',
    authDomain: 'gobuddy-at1435.firebaseapp.com',
    storageBucket: 'gobuddy-at1435.firebasestorage.app',
    measurementId: 'G-NBR2QXBDHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqb54PkbP-L5atLFS0NRokMRgJL2MrQU',
    appId: '1:1015423722551:android:e3e3ba040120440579cbb2',
    messagingSenderId: '1015423722551',
    projectId: 'gobuddy-at1435',
    storageBucket: 'gobuddy-at1435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbfJ-I3BR3LxrHqA_zHJFOSyv-ffsd6bA',
    appId: '1:1015423722551:ios:6c82009a1d0c714879cbb2',
    messagingSenderId: '1015423722551',
    projectId: 'gobuddy-at1435',
    storageBucket: 'gobuddy-at1435.firebasestorage.app',
    iosBundleId: 'com.example.gobuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbfJ-I3BR3LxrHqA_zHJFOSyv-ffsd6bA',
    appId: '1:1015423722551:ios:6c82009a1d0c714879cbb2',
    messagingSenderId: '1015423722551',
    projectId: 'gobuddy-at1435',
    storageBucket: 'gobuddy-at1435.firebasestorage.app',
    iosBundleId: 'com.example.gobuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTlI_cmmqjf5FPHHUcMUHq56pwifwq_FE',
    appId: '1:1015423722551:web:1e78f4c18b91d21879cbb2',
    messagingSenderId: '1015423722551',
    projectId: 'gobuddy-at1435',
    authDomain: 'gobuddy-at1435.firebaseapp.com',
    storageBucket: 'gobuddy-at1435.firebasestorage.app',
    measurementId: 'G-65G6YBEK51',
  );
}
